import type { Metadata } from "next";
import { Orbitron, Work_Sans } from "next/font/google";
import "./globals.css";

const workSane = Work_Sans({
	variable: "--font-work-sans",
	subsets: ["latin"],
});

const anta = Orbitron({
	subsets: ["latin"],
	variable: "--font-display",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${workSane.variable} ${anta.variable} font-sans antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
